### PR TITLE
license: add ASF header.

### PR DESCRIPTION
**Pull request by moonming**

### CODE REVIEW

**Comment by moonming** [comment]
@juzhiyuan Please help check to make sure I have not missed some files.
I checked all `.ts`,`.js` and `.vue` files.
And one more thing, how can I add ASF header for dashboard-built files?

**Comment by juzhiyuan** [comment]
@moonming I will check if we miss some files tomorrow morning; 

New changes will be taken effect to dashboard_built repo once we trigger Travis CI for master branch.

**Comment by juzhiyuan** [comment]
image

Building.

**Comment by juzhiyuan** [comment]
@moonming These has occurred one error: Travis cannot find `dashboard_license` file.

Just for sure, which license is suited for `dashboard_built` repo? MIT or Apache 2.0?

image

**Comment by moonming** [comment]
> @moonming These has occurred one error: Travis cannot find `dashboard_license` file.
> 
I deleted this file, [`LICENSE`](https://github.com/iresty/apisix_dashboard/blob/master/LICENSE) already contains the license content. 

> Just for sure, which license is suited for `dashboard_built` repo? MIT or Apache 2.0? then I will update the shell commands under Travis CI.
Apache 2.0 is good enough.
> 
> image
> 
> image

**Comment by juzhiyuan** [comment]
I will do some changes soon.

**Comment by juzhiyuan** [comment]
> @juzhiyuan Please help check to make sure I have not missed some files.
> I checked all `.ts`,`.js` and `.vue` files.
> And one more thing, how can I add ASF header for dashboard-built files?

All files have been added ASF header. One more thing, it seems that the Vue build process will remove unnecessary comments, so `dashboard_built` codes don't have ASF header.

**Comment by juzhiyuan** [comment]
The `dashboard_built` repo is now under the Apache 2.0 License, do we still have to include ASF header in Production files?

https://github.com/iresty/apisix_dashboard_built

image

**Comment by moonming** [comment]
yes, we need add ASF header in every source code files.

**Comment by juzhiyuan** [comment]
Ok, then I need to do some hacks in Travis script.

**Comment by juzhiyuan** [comment]
> @juzhiyuan Please help check to make sure I have not missed some files.
> I checked all `.ts`,`.js` and `.vue` files.
> And one more thing, how can I add ASF header for dashboard-built files?

All production files under `dashboard_built` repo have been added ASF header automatically.

Just for sure, if we need to add ASF header to CSS files?

**Pull request merged**
