### PR TITLE
added shell for adding ASF header

### PR DESCRIPTION
**Pull request by juzhiyuan**

### CODE REVIEW

**Comment by moonming** [comment]
@juzhiyuan I need add asf header to `*.css` files too.

**Comment by juzhiyuan** [comment]
@moonming All JS & CSS files in production repo `dashboard_built` have been added ASF header automatically.

image

**Comment by moonming** [comment]
https://github.com/iresty/apisix_dashboard_built/blob/master/index.html
not contains asf header.

**Comment by juzhiyuan** [comment]
@moonming just added. I thought only JS & CSS need ASF header 😅

**Comment by moonming** [comment]
Even markdown files also need ASF header.

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2019年10月27日周日 下午10:58写道：

**Comment by juzhiyuan** [comment]
@moonming `apisix_dashboard_built` repo doesn't have Markdown files.

**Pull request merged**
